// Build driver: `node build.mjs` (production → dist/) or `node build.mjs --watch` (dev: rebuild on save,
// hot-reload the extension and refresh open NYT game tabs through a local WebSocket).
import { context } from "esbuild";
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, watch as fsWatch, writeFileSync } from "node:fs";
import { createConnection } from "node:net";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { WebSocketServer } from "ws";

const root = dirname(fileURLToPath(import.meta.url));
const dev = process.argv.includes("--watch");
/** Output directory. `pnpm dev` owns dist/; a side build goes elsewhere: NYTE_OUT=dist-prod pnpm build */
const OUT = join(root, process.env.NYTE_OUT ?? "dist");
const PORT = Number(process.env.NYTE_DEV_PORT ?? 35729);

function devServerRunning(port) {
  return new Promise((resolve) => {
    const socket = createConnection({ port, host: "127.0.0.1" });
    socket.setTimeout(500);
    socket.once("connect", () => { socket.destroy(); resolve(true); });
    socket.once("error", () => resolve(false));
    socket.once("timeout", () => { socket.destroy(); resolve(false); });
  });
}

// A production build into dist/ while `pnpm dev` is serving from it would silently replace the
// dev bundles (which carry the reload client) and break hot reload until the next manual reload.
if (!dev && process.env.NYTE_OUT === undefined && !process.argv.includes("--force") && (await devServerRunning(PORT))) {
  console.error(
    `[nyte] a dev reload server is listening on port ${PORT}, so \`pnpm dev\` is running and owns dist/.\n` +
      "       A production build would overwrite its output and break hot reload.\n" +
      "       Build elsewhere instead:  NYTE_OUT=dist-prod pnpm build   (or pass --force to overwrite).",
  );
  process.exit(1);
}

/** Built games (directory names under src/games). `_template` is intentionally excluded. */
const GAMES = ["crossword", "connections", "spelling-bee", "wordle"];
/** Non-game page modules (directory names under src/pages). */
const PAGES = ["crosswords-hub", "crosswords-archive", "subscription-offer"];

function buildManifest() {
  const manifest = JSON.parse(readFileSync(join(root, "manifest.json"), "utf8"));
  if (dev) {
    manifest.version_name = "dev";
    // Only the reload socket; never a nytimes.com host permission (see README "Permissions").
    manifest.host_permissions = [...(manifest.host_permissions ?? []), "http://localhost/*", "ws://localhost/*"];
  }
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "manifest.json"), JSON.stringify(manifest, null, 2));
  return manifest;
}

function copyStatic() {
  mkdirSync(join(OUT, "popup"), { recursive: true });
  copyFileSync(join(root, "src/popup/popup.html"), join(OUT, "popup/popup.html"));
  // Extension icons (original artwork, generated by scripts/make-icons.mjs → `pnpm icons`).
  mkdirSync(join(OUT, "icons"), { recursive: true });
  for (const size of [16, 32, 48, 128]) copyFileSync(join(root, `src/icons/icon-${size}.png`), join(OUT, `icons/icon-${size}.png`));
}

function assertManifestFiles(manifest) {
  const files = new Set();
  for (const cs of manifest.content_scripts ?? []) for (const f of [...(cs.js ?? []), ...(cs.css ?? [])]) files.add(f);
  if (manifest.background?.service_worker) files.add(manifest.background.service_worker);
  if (manifest.action?.default_popup) files.add(manifest.action.default_popup);
  for (const icon of Object.values(manifest.icons ?? {})) files.add(icon);
  for (const icon of Object.values(manifest.action?.default_icon ?? {})) files.add(icon);
  const missing = [...files].filter((f) => !existsSync(join(OUT, f)));
  if (missing.length) {
    console.error("[nyte] build outputs referenced by the manifest are missing:", missing);
    process.exit(1);
  }
}

function startReloadServer() {
  const wss = new WebSocketServer({ port: PORT });
  wss.on("error", (err) => {
    if (err.code === "EADDRINUSE") {
      console.error(`[nyte] port ${PORT} is in use; set NYTE_DEV_PORT to another port`);
      process.exit(1);
    }
    throw err;
  });
  wss.on("listening", () => console.log(`[nyte] reload server listening on ws://localhost:${PORT}`));

  // Chrome disables an extension that calls runtime.reload() more than 5 times in 10 s (unpacked too),
  // so broadcasts are coalesced and spaced out; the trailing edge guarantees the last build wins.
  const MIN_INTERVAL = 2500;
  const COALESCE = 200;
  let lastSent = 0;
  let timer = null;
  const send = () => {
    timer = null;
    lastSent = Date.now();
    const message = JSON.stringify({ type: "reload", buildId: lastSent });
    let clients = 0;
    for (const client of wss.clients) {
      if (client.readyState === 1) {
        client.send(message);
        clients++;
      }
    }
    console.log(`[nyte] reload sent to ${clients} client(s)`);
  };
  const broadcast = () => {
    if (timer) return;
    timer = setTimeout(send, Math.max(COALESCE, lastSent + MIN_INTERVAL - Date.now()));
  };
  // Keeps the MV3 service worker alive (WebSocket activity resets its 30 s idle timer).
  setInterval(() => {
    for (const client of wss.clients) if (client.readyState === 1) client.send(JSON.stringify({ type: "ping" }));
  }, 20_000).unref();
  return { broadcast };
}

function reloadPlugin(server) {
  return {
    name: "nyte-reload",
    setup(build) {
      build.onEnd((result) => {
        if (result.errors.length === 0) server.broadcast();
      });
    },
  };
}

const server = dev ? startReloadServer() : null;
const common = {
  bundle: true,
  target: ["chrome120"],
  outdir: OUT,
  define: { __DEV__: dev ? "true" : "false", __NYTE_DEV_PORT__: String(PORT) },
  sourcemap: dev ? "inline" : false,
  minify: !dev,
  logLevel: "info",
  plugins: server ? [reloadPlugin(server)] : [],
};

// CSS files are plain entry points (no preprocessing) so watch mode covers stylesheet edits.
const moduleEntries = (dir, ids) => ({
  ...Object.fromEntries(ids.map((id) => [`${dir}/${id}/content`, `src/${dir}/${id}/content.ts`])),
  ...Object.fromEntries(
    ids.filter((id) => existsSync(join(root, `src/${dir}/${id}/dark.css`))).map((id) => [`${dir}/${id}/dark`, `src/${dir}/${id}/dark.css`]),
  ),
});
const entryPoints = {
  ...moduleEntries("games", GAMES),
  ...moduleEntries("pages", PAGES),
  "styles/theme": "src/styles/theme.css",
  "popup/popup": "src/popup/popup.ts",
  "popup/styles": "src/popup/popup.css",
};

rmSync(OUT, { recursive: true, force: true });
const manifest = buildManifest();
copyStatic();

const iife = await context({ ...common, format: "iife", entryPoints });
const esm = await context({ ...common, format: "esm", entryPoints: { "background/service-worker": "src/background/service-worker.ts" } });

if (dev) {
  await Promise.all([iife.watch(), esm.watch()]);
  const onStatic = (file) => {
    try {
      buildManifest();
      copyStatic();
      console.log(`[nyte] ${file} copied`);
      server.broadcast();
    } catch (err) {
      console.error("[nyte] static copy failed", err);
    }
  };
  // Watch the directories (editors often save via rename, which breaks single-file watchers).
  fsWatch(root, (_event, file) => file === "manifest.json" && onStatic(file));
  fsWatch(join(root, "src/popup"), (_event, file) => file === "popup.html" && onStatic(file));
  console.log(`[nyte] watching src/ — load ${OUT} once via chrome://extensions → Load unpacked`);
} else {
  await Promise.all([iife.rebuild(), esm.rebuild()]);
  await Promise.all([iife.dispose(), esm.dispose()]);
  assertManifestFiles(manifest);
  console.log("[nyte] build complete → dist/");
}
